# Generated by Django 5.1.15 on 2026-06-30 03:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpus', '0019_nodechunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended')], default='trial', max_length=16)),
                ('brand_name', models.CharField(blank=True, max_length=120)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('allowed_source_slugs', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=100), blank=True, default=list, size=None)),
                ('system_prompt_key', models.CharField(blank=True, max_length=64)),
                ('brand_name', models.CharField(blank=True, max_length=120)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('primary_color', models.CharField(blank=True, help_text='Hex e.g. #0b3d2e. Blank = flagship default.', max_length=9)),
                ('accent_color', models.CharField(blank=True, max_length=9)),
                ('login_tagline', models.CharField(blank=True, max_length=200)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('disclaimer', models.TextField(blank=True, help_text="'Not legal advice' copy shown in-app.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='corpus.jurisdiction')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrgMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'org'), name='uniq_membership_per_user_org')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], default='trial', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenancy.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenancy.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('org__isnull', False), ('user__isnull', True)), models.Q(('org__isnull', True), ('user__isnull', False)), _connector='OR'), name='subscription_org_xor_user'), models.UniqueConstraint(condition=models.Q(('org__isnull', False)), fields=('org', 'product'), name='uniq_org_product_subscription'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product'), name='uniq_user_product_subscription')],
            },
        ),
    ]
