# Generated by Django 5.1.15 on 2026-04-29 00:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corpus", "0001_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jurisdiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="NodeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("label_singular", models.CharField(max_length=50)),
                ("label_plural", models.CharField(blank=True, max_length=50)),
                ("abbreviation", models.CharField(blank=True, max_length=20)),
                ("level", models.PositiveSmallIntegerField()),
                (
                    "citation_segment_template",
                    models.CharField(blank=True, max_length=100),
                ),
            ],
            options={
                "ordering": ("source", "level"),
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.CharField(max_length=50)),
                ("path", models.CharField(db_index=True, max_length=500)),
                ("heading", models.CharField(blank=True, max_length=500)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                ("is_repealed", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="corpus.node",
                    ),
                ),
                (
                    "node_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nodes",
                        to="corpus.nodetype",
                    ),
                ),
            ],
            options={
                "ordering": ("source", "path"),
            },
        ),
        migrations.CreateModel(
            name="NodeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body_text", models.TextField()),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("enacted_by", models.CharField(blank=True, max_length=200)),
                ("content_hash", models.CharField(max_length=64)),
                ("embedding_source_hash", models.CharField(blank=True, max_length=64)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="corpus.node",
                    ),
                ),
            ],
            options={
                "ordering": ("node", "-effective_from"),
            },
        ),
        migrations.CreateModel(
            name="CrossReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_text", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("internal", "Internal"), ("external", "External")],
                        default="internal",
                        max_length=16,
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_references",
                        to="corpus.node",
                    ),
                ),
                (
                    "from_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_references",
                        to="corpus.nodeversion",
                    ),
                ),
            ],
            options={
                "ordering": ("from_version",),
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=200)),
                ("citation_abbreviation", models.CharField(max_length=50)),
                ("official_url_template", models.CharField(blank=True, max_length=500)),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sources",
                        to="corpus.jurisdiction",
                    ),
                ),
            ],
            options={
                "ordering": ("jurisdiction__name", "name"),
            },
        ),
        migrations.AddField(
            model_name="nodetype",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="node_types",
                to="corpus.source",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="corpus.source",
            ),
        ),
        migrations.CreateModel(
            name="CitationFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("template", models.CharField(max_length=500)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citation_formats",
                        to="corpus.source",
                    ),
                ),
            ],
            options={
                "ordering": ("source", "key"),
            },
        ),
        migrations.AddIndex(
            model_name="nodeversion",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="nodeversion_search_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                fields=("jurisdiction", "slug"), name="uniq_source_per_jurisdiction"
            ),
        ),
        migrations.AddConstraint(
            model_name="nodetype",
            constraint=models.UniqueConstraint(
                fields=("source", "key"), name="uniq_nodetype_per_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                fields=("source", "path"), name="uniq_node_path_per_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="citationformat",
            constraint=models.UniqueConstraint(
                fields=("source", "key"), name="uniq_citation_format_per_source"
            ),
        ),
    ]
