# Generated by Django 5.1.15 on 2026-06-03 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0008_drop_body_text_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=200)),
                ('as_of_date', models.DateField(help_text="Point-in-time date this edition's text is resolved at.")),
                ('published_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='corpus.source')),
            ],
            options={
                'ordering': ('source', '-year'),
                'constraints': [models.UniqueConstraint(fields=('source', 'year'), name='uniq_edition_per_source_year'), models.UniqueConstraint(fields=('source', 'as_of_date'), name='uniq_edition_asof_per_source')],
            },
        ),
    ]
