# Generated by Django 5.1.15 on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0009_edition'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nodeversion',
            constraint=models.UniqueConstraint(
                condition=models.Q(effective_to__isnull=True),
                fields=('node', 'content_hash'),
                name='uniq_open_nodeversion_per_node_hash',
            ),
        ),
    ]
