# Generated by Django 5.1.15 on 2026-06-04 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0012_nodeversion_single_open_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('court_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Supreme'), (2, 'Appellate'), (3, 'Trial')], help_text='Authority rank; a lower number binds higher-numbered courts.')),
            ],
            options={
                'ordering': ('jurisdiction__name', 'level'),
            },
        ),
        migrations.CreateModel(
            name='ReporterCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_citation_id', models.BigIntegerField(unique=True)),
                ('cl_cluster_id', models.BigIntegerField()),
                ('reporter', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=20)),
                ('page', models.CharField(max_length=30)),
                ('type', models.PositiveSmallIntegerField(blank=True, help_text='CourtListener citation-type enum.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='crossreference',
            name='source',
            field=models.CharField(choices=[('statute', 'Statute prose'), ('caselaw_link', 'Caselaw inline link'), ('caselaw_graph', 'Caselaw citation graph')], default='statute', help_text='Extractor that produced this edge; scopes idempotent rebuilds.', max_length=20),
        ),
        migrations.AddField(
            model_name='crossreference',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='crossreference',
            constraint=models.UniqueConstraint(condition=models.Q(('to_node__isnull', False)), fields=('from_version', 'to_node', 'source'), name='uniq_crossref_internal_per_source'),
        ),
        migrations.AddConstraint(
            model_name='crossreference',
            constraint=models.UniqueConstraint(condition=models.Q(('to_node__isnull', True)), fields=('from_version', 'external_text', 'source'), name='uniq_crossref_external_per_source'),
        ),
        migrations.AddField(
            model_name='court',
            name='jurisdiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courts', to='corpus.jurisdiction'),
        ),
        migrations.AddField(
            model_name='reportercitation',
            name='to_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporter_citations', to='corpus.node'),
        ),
        migrations.AddIndex(
            model_name='reportercitation',
            index=models.Index(fields=['reporter', 'volume', 'page'], name='reportercite_rvp_lookup'),
        ),
    ]
