# Generated by Django 5.1.15 on 2026-06-04 05:28

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0013_court_reportercitation_crossreference_source_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='node',
            index=django.contrib.postgres.indexes.GinIndex(fields=['source_metadata'], name='node_source_metadata_gin', opclasses=['jsonb_path_ops']),
        ),
    ]
