# Generated by Django 5.1.15 on 2026-06-04 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0015_seed_iowa_courts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportercitation',
            name='to_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter_citations', to='corpus.node'),
        ),
    ]
