# Generated by Django 5.1.15 on 2026-06-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0016_alter_reportercitation_to_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeversion',
            name='body_segments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
