# Generated by Django 5.1.15 on 2026-06-06 15:53

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


# HNSW index on the chunk embedding, mirroring corpus_nodeversion (migration
# 0006): vector_cosine_ops, pgvector defaults (m=16, ef_construction=64). Built
# empty here — chunks are embedded by a later job — so the build is instant; tune
# m/ef once the caselaw chunk corpus is loaded and we have eval numbers.
CREATE_HNSW = """
CREATE INDEX IF NOT EXISTS corpus_nodechunk_embedding_hnsw
    ON corpus_nodechunk USING hnsw (embedding vector_cosine_ops);
"""

DROP_HNSW = """
DROP INDEX IF EXISTS corpus_nodechunk_embedding_hnsw;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0018_node_caselaw_date_filed_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('body_text', models.TextField()),
                ('context_header', models.TextField(blank=True)),
                ('char_start', models.PositiveIntegerField()),
                ('char_end', models.PositiveIntegerField()),
                ('token_count', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding_source_hash', models.CharField(blank=True, max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='corpus.nodeversion')),
            ],
            options={
                'ordering': ('version', 'ordinal'),
                'constraints': [models.UniqueConstraint(fields=('version', 'ordinal'), name='uniq_chunk_ordinal_per_version')],
            },
        ),
        migrations.RunSQL(sql=CREATE_HNSW, reverse_sql=DROP_HNSW),
    ]
