# Generated by Django 5.1.15 on 2026-07-10 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0019_nodechunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseResearchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('web_currency', 'Web currency check')], default='web_currency', max_length=32)),
                ('status', models.CharField(choices=[('clear', 'Clear (good law per source)'), ('adverse', 'Adverse finding')], max_length=16)),
                ('adverse_kind', models.CharField(blank=True, help_text='overruled | superseded_by_statute | caution', max_length=32)),
                ('claimed_by', models.CharField(blank=True, help_text='The overruling case / superseding statute the source names.', max_length=300)),
                ('evidence', models.TextField(blank=True)),
                ('source_url', models.CharField(blank=True, max_length=500)),
                ('corpus_verified', models.BooleanField(default=False)),
                ('corpus_matches', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved (real)'), ('rejected', 'Rejected (false alarm)')], default='pending', max_length=16)),
                ('model', models.CharField(blank=True, max_length=40)),
                ('checked_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(help_text='The decision (cluster) node the note is about.', on_delete=django.db.models.deletion.CASCADE, related_name='research_notes', to='corpus.node')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('node', 'kind'), name='research_note_one_per_node_kind')],
            },
        ),
    ]
