# Generated by Django 5.1.15 on 2026-07-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0020_caseresearchnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresearchnote',
            name='kind',
            field=models.CharField(choices=[('web_currency', 'Web currency check'), ('construction', 'Construction / scope note')], default='web_currency', max_length=32),
        ),
    ]
