# Generated by Django 5.1.15 on 2026-07-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0022_seed_iowa_admin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossreference',
            name='source',
            field=models.CharField(choices=[('statute', 'Statute prose'), ('caselaw_link', 'Caselaw inline link'), ('caselaw_graph', 'Caselaw citation graph'), ('reg_enabling', 'Regulation enabling statute')], default='statute', help_text='Extractor that produced this edge; scopes idempotent rebuilds.', max_length=20),
        ),
    ]
