# Generated by Django 5.1.15 on 2026-07-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0024_seed_iowa_acts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresearchnote',
            name='kind',
            field=models.CharField(choices=[('web_currency', 'Web currency check'), ('construction', 'Construction / scope note'), ('act_supersession', 'Superseded by session law')], default='web_currency', max_length=32),
        ),
        migrations.AlterField(
            model_name='crossreference',
            name='source',
            field=models.CharField(choices=[('statute', 'Statute prose'), ('caselaw_link', 'Caselaw inline link'), ('caselaw_graph', 'Caselaw citation graph'), ('reg_enabling', 'Regulation enabling statute'), ('act_affects', 'Act affects statute')], default='statute', help_text='Extractor that produced this edge; scopes idempotent rebuilds.', max_length=20),
        ),
    ]
