# Generated by Django 5.1.15 on 2026-07-09 20:36

import apps.mail.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(help_text='The full inbox address, e.g. assistant@mail.nick.law. Plus-tags are stripped before matching, so this is the base form.', max_length=254, unique=True)),
                ('display_name', models.CharField(default='Hudson Research Assistant', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('mode', models.CharField(choices=[('allowlist', 'Allowlist only'), ('entitled', 'Entitled users')], default='allowlist', max_length=16)),
                ('model', models.CharField(default='gpt-5-mini', max_length=40)),
                ('signature', models.TextField(blank=True, help_text='Optional text above the standard footer.')),
                ('disclaimer', models.TextField(blank=True, help_text='Extra per-product disclaimer appended to the footer.')),
                ('max_daily_per_sender', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, help_text="Scope lock + entitlement source. NULL = flagship (full corpus, any registered user in 'entitled' mode).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assistant_addresses', to='tenancy.product')),
            ],
            options={
                'verbose_name_plural': 'assistant addresses',
            },
        ),
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.mail.models.new_thread_token, max_length=16, unique=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('suppressed', 'Suppressed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='mail.assistantaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=100, unique=True)),
                ('rfc_message_id', models.CharField(blank=True, max_length=512)),
                ('in_reply_to', models.CharField(blank=True, max_length=512)),
                ('references', models.TextField(blank=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.CharField(blank=True, max_length=254)),
                ('mailbox_hash', models.CharField(blank=True, max_length=64)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('spf_pass', models.BooleanField(null=True)),
                ('dkim_pass', models.BooleanField(null=True)),
                ('spam_score', models.FloatField(blank=True, null=True)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('answered', 'Answered'), ('rejected', 'Rejected'), ('ignored', 'Ignored'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('reject_reason', models.CharField(blank=True, max_length=200)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound', to='mail.assistantaddress')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound', to='mail.emailthread')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=512, unique=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_reply_to_inbound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='mail.inboundemail')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound', to='mail.emailthread')),
            ],
        ),
        migrations.CreateModel(
            name='AddressAllowlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowlist', to='mail.assistantaddress')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('address', 'email'), name='allowlist_unique_per_address')],
            },
        ),
    ]
