# Generated by Django 5.1.15 on 2026-06-02 22:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('event_type', models.CharField(choices=[('login_success', 'Login success'), ('login_failure', 'Login failure'), ('login_locked_out', 'Login blocked (locked out)'), ('logout', 'Logout'), ('register', 'Registration'), ('register_blocked', 'Registration blocked (throttled)'), ('password_change', 'Password change'), ('profile_change', 'Profile / email change'), ('api_key_create', 'API key created'), ('api_key_revoke', 'API key revoked')], db_index=True, max_length=32)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('blocked', 'Blocked')], default='success', max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='accounts_au_event_t_028052_idx'), models.Index(fields=['actor_email', 'created_at'], name='accounts_au_actor_e_fb430a_idx')],
            },
        ),
    ]
