# Generated by Django 5.1.15 on 2026-06-05 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('country', models.CharField(blank=True, default='US', max_length=2)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, choices=[('attorney', 'Attorney'), ('paralegal', 'Paralegal'), ('law_clerk', 'Law clerk'), ('law_student', 'Law student'), ('researcher', 'Legal researcher'), ('other', 'Other')], max_length=16)),
                ('bar_number', models.CharField(blank=True, max_length=64)),
                ('primary_jurisdiction', models.CharField(blank=True, max_length=64)),
                ('timezone', models.CharField(blank=True, default='America/Chicago', max_length=64)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=8)),
                ('default_search_scope', models.CharField(choices=[('all', 'Everything'), ('cases', 'Case law only'), ('statutes', 'Statutes & codes only'), ('secondary', 'Secondary sources only')], default='all', max_length=16)),
                ('citation_style', models.CharField(choices=[('bluebook', 'Bluebook (21st ed.)'), ('alwd', 'ALWD Guide'), ('iowa', 'Iowa local rules')], default='bluebook', max_length=16)),
                ('verify_citations', models.BooleanField(default=True)),
                ('weekly_digest', models.BooleanField(default=True)),
                ('product_news', models.BooleanField(default=False)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('tos_version', models.CharField(blank=True, max_length=32)),
                ('tos_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login success'), ('login_failure', 'Login failure'), ('login_locked_out', 'Login blocked (locked out)'), ('logout', 'Logout'), ('register', 'Registration'), ('register_blocked', 'Registration blocked (throttled)'), ('password_change', 'Password change'), ('profile_change', 'Profile / email change'), ('settings_change', 'Settings / preferences change'), ('tos_accepted', 'Terms of Service accepted'), ('onboarding_completed', 'Onboarding completed'), ('api_key_create', 'API key created'), ('api_key_revoke', 'API key revoked')], db_index=True, max_length=32),
        ),
    ]
