# Generated by Django 5.1.15 on 2026-07-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_profiles_and_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_budget_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
