# Generated by Django 5.1.15 on 2026-07-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_monthly_budget_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login success'), ('login_failure', 'Login failure'), ('login_locked_out', 'Login blocked (locked out)'), ('logout', 'Logout'), ('register', 'Registration'), ('register_blocked', 'Registration blocked (throttled)'), ('password_change', 'Password change'), ('profile_change', 'Profile / email change'), ('settings_change', 'Settings / preferences change'), ('tos_accepted', 'Terms of Service accepted'), ('onboarding_completed', 'Onboarding completed'), ('api_key_create', 'API key created'), ('api_key_revoke', 'API key revoked'), ('admin_user_change', 'Admin changed a user account')], db_index=True, max_length=32),
        ),
    ]
