# Generated by Django 5.1.15 on 2026-07-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_org_audit_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login success'), ('login_failure', 'Login failure'), ('login_locked_out', 'Login blocked (locked out)'), ('logout', 'Logout'), ('register', 'Registration'), ('register_blocked', 'Registration blocked (throttled)'), ('password_change', 'Password change'), ('profile_change', 'Profile / email change'), ('settings_change', 'Settings / preferences change'), ('tos_accepted', 'Terms of Service accepted'), ('onboarding_completed', 'Onboarding completed'), ('api_key_create', 'API key created'), ('api_key_revoke', 'API key revoked'), ('admin_user_change', 'Admin changed a user account'), ('org_member_add', 'Org member added'), ('org_member_remove', 'Org member removed'), ('org_role_change', 'Org member role changed'), ('org_invite_create', 'Org invitation sent'), ('org_invite_revoke', 'Org invitation revoked'), ('org_invite_accept', 'Org invitation accepted'), ('org_update', 'Organization updated'), ('edms_connect', 'EDMSpro cloud account connected'), ('edms_disconnect', 'EDMSpro cloud account disconnected'), ('edms_opt_in', 'EDMSpro contribution opt-in enabled'), ('edms_opt_out', 'EDMSpro contribution opt-in disabled'), ('edms_contribute', 'EDMSpro filing contributed'), ('edms_purge', 'EDMSpro contributions purged')], db_index=True, max_length=32),
        ),
    ]
