# Generated by Django 5.1.15 on 2026-07-28 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EdmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_provider', models.CharField(blank=True, choices=[('onedrive', 'OneDrive'), ('gdrive', 'Google Drive')], default='onedrive', max_length=16)),
                ('default_destination_folder_id', models.CharField(blank=True, default='', max_length=512)),
                ('default_destination_path', models.CharField(blank=True, default='', max_length=1024)),
                ('naming_template', models.CharField(default='{date}_{case_num}_{doc_title}', max_length=256)),
                ('case_folder_template', models.CharField(default='{case_number}', max_length=256)),
                ('crowdsource_opt_in', models.BooleanField(default=False)),
                ('crowdsource_opt_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edms_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EDMSpro settings',
                'verbose_name_plural': 'EDMSpro settings',
            },
        ),
        migrations.CreateModel(
            name='CaseFolderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, max_length=64)),
                ('provider', models.CharField(blank=True, choices=[('onedrive', 'OneDrive'), ('gdrive', 'Google Drive')], default='', max_length=16)),
                ('folder_id', models.CharField(blank=True, default='', max_length=512)),
                ('folder_path', models.CharField(blank=True, default='', max_length=1024)),
                ('naming_template', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edms_case_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('case_number',),
                'constraints': [models.UniqueConstraint(fields=('user', 'case_number'), name='edms_uniq_user_case')],
            },
        ),
        migrations.CreateModel(
            name='CloudIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('onedrive', 'OneDrive'), ('gdrive', 'Google Drive')], max_length=16)),
                ('access_token_enc', models.TextField(blank=True, default='')),
                ('refresh_token_enc', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('account_email', models.CharField(blank=True, default='', max_length=320)),
                ('account_name', models.CharField(blank=True, default='', max_length=200)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('needs_reconnect', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edms_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='edms_uniq_user_provider')],
            },
        ),
        migrations.CreateModel(
            name='CrowdsourceArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket', models.CharField(max_length=128)),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('case_number', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('case_type', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('doc_type', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('doc_title', models.CharField(blank=True, default='', max_length=512)),
                ('county', models.CharField(blank=True, default='', max_length=128)),
                ('row_date', models.DateField(blank=True, null=True)),
                ('safety_flags', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('stored', 'Stored (awaiting redaction policy)'), ('purged', 'Purged')], default='stored', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edms_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['submitted_by', '-created_at'], name='edms_crowds_submitt_7a52a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='FilingSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, max_length=64)),
                ('case_type', models.CharField(blank=True, default='', max_length=128)),
                ('docket_num', models.CharField(blank=True, default='', max_length=64)),
                ('cms_doc_id', models.CharField(blank=True, default='', max_length=64)),
                ('doc_title', models.CharField(blank=True, default='', max_length=512)),
                ('doc_type', models.CharField(blank=True, default='', max_length=128)),
                ('row_date', models.DateField(blank=True, null=True)),
                ('filer', models.CharField(blank=True, default='', max_length=256)),
                ('county', models.CharField(blank=True, default='', max_length=128)),
                ('judge', models.CharField(blank=True, default='', max_length=256)),
                ('provider', models.CharField(blank=True, choices=[('onedrive', 'OneDrive'), ('gdrive', 'Google Drive')], default='', max_length=16)),
                ('status', models.CharField(choices=[('pending_upload', 'Awaiting upload'), ('success', 'Success'), ('failed', 'Failed')], default='pending_upload', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('destination_path', models.CharField(blank=True, default='', max_length=1024)),
                ('destination_filename', models.CharField(blank=True, default='', max_length=256)),
                ('cloud_item_id', models.CharField(blank=True, default='', max_length=128)),
                ('cloud_web_url', models.URLField(blank=True, default='', max_length=1024)),
                ('upload_expires_at', models.DateTimeField(blank=True, null=True)),
                ('byte_size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edms_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='edms_filing_user_id_b62982_idx'), models.Index(fields=['user', 'status'], name='edms_filing_user_id_c2dfd1_idx')],
            },
        ),
    ]
