# Generated by Django 5.1.15 on 2026-06-03 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('cl_bulk_clusters', 'CourtListener bulk opinion-clusters CSV'), ('cl_bulk_opinions', 'CourtListener bulk opinions CSV'), ('cl_bulk_citations', 'CourtListener bulk citations CSV'), ('cl_bulk_dockets', 'CourtListener bulk dockets CSV')], max_length=32)),
                ('code_year', models.PositiveIntegerField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('fetched_from', models.CharField(blank=True, max_length=500)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('storage_path', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-fetched_at',),
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('acquire', 'Acquire'), ('write', 'Write')], default='acquire', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('nodes_added', models.PositiveIntegerField(default=0)),
                ('nodes_amended', models.PositiveIntegerField(default=0)),
                ('nodes_repealed', models.PositiveIntegerField(default=0)),
                ('nodes_unchanged', models.PositiveIntegerField(default=0)),
                ('last_cluster_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('log', models.TextField(blank=True)),
                ('raw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='ingestion_caselaw.rawingestion')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
    ]
