# Generated by Django 5.1.15 on 2026-07-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion_caselaw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrun',
            name='cursor_date',
            field=models.DateTimeField(blank=True, help_text="Incremental-update high-water mark: everything CL added (date_created) before this instant has been swept. Set only on phase='update' runs; the next run resumes from the latest approved cursor minus an overlap window.", null=True),
        ),
        migrations.AlterField(
            model_name='ingestionrun',
            name='phase',
            field=models.CharField(choices=[('acquire', 'Acquire'), ('write', 'Write'), ('update', 'Incremental update')], default='acquire', max_length=16),
        ),
    ]
