# Generated by Django 5.1.15 on 2026-07-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(help_text="Mono eyebrow on cards, e.g. 'Grounding', 'Search', 'Engineering'.", max_length=100)),
                ('lede', models.TextField(blank=True)),
                ('excerpt', models.TextField()),
                ('body_md', models.TextField(help_text='Article body, GitHub-flavored markdown.')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('author_name', models.CharField(default='Nick Hudson', max_length=120)),
                ('author_title', models.CharField(default='Founder, Hudson Legal Technologies', max_length=200)),
                ('published', models.BooleanField(default=False, help_text='Only published articles appear on the site.')),
                ('published_at', models.DateField(blank=True, null=True)),
                ('read_minutes', models.PositiveIntegerField(default=0, help_text='0 = auto-compute from word count on save.')),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('page', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal triage notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
