# Generated by Django 5.1.15 on 2026-09-19 16:58

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # pg_trgm is already installed by apps/corpus/0001_extensions, but this
        # app must not depend on that app's migration order: CREATE EXTENSION
        # IF NOT EXISTS is idempotent, and the two trigram GIN indexes below
        # cannot be built without it.
        TrigramExtension(),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('table', 'Local table'), ('external', 'External lookup')], default='table', max_length=16)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('license', models.CharField(blank=True, max_length=120)),
                ('attribution_text', models.TextField(blank=True)),
                ('refresh_cadence', models.CharField(blank=True, max_length=60)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'OK'), ('skipped', 'Skipped'), ('aborted', 'Aborted'), ('failed', 'Failed')], default='running', max_length=16)),
                ('source_last_modified', models.DateTimeField(blank=True, null=True)),
                ('file_sha256', models.CharField(blank=True, max_length=64)),
                ('file_bytes', models.BigIntegerField(blank=True, null=True)),
                ('row_count', models.IntegerField(default=0)),
                ('inserted', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('deactivated', models.IntegerField(default=0)),
                ('reactivated', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='resources.dataset')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BusinessEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_number', models.CharField(max_length=12, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('name_normalized', models.CharField(max_length=255)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('registered_agent', models.CharField(blank=True, max_length=255)),
                ('agent_normalized', models.CharField(blank=True, max_length=255)),
                ('ra_address_1', models.CharField(blank=True, max_length=160)),
                ('ra_address_2', models.CharField(blank=True, max_length=160)),
                ('ra_city', models.CharField(blank=True, max_length=80)),
                ('ra_state', models.CharField(blank=True, max_length=32)),
                ('ra_zip', models.CharField(blank=True, max_length=16)),
                ('home_office', models.CharField(blank=True, max_length=160)),
                ('ho_address_1', models.CharField(blank=True, max_length=160)),
                ('ho_address_2', models.CharField(blank=True, max_length=160)),
                ('ho_city', models.CharField(blank=True, max_length=120)),
                ('ho_state', models.CharField(blank=True, max_length=32)),
                ('ho_zip', models.CharField(blank=True, max_length=16)),
                ('ho_country', models.CharField(blank=True, max_length=16)),
                ('ra_lat', models.FloatField(blank=True, null=True)),
                ('ra_lon', models.FloatField(blank=True, null=True)),
                ('ho_lat', models.FloatField(blank=True, null=True)),
                ('ho_lon', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen', models.DateField()),
                ('last_seen', models.DateField()),
                ('deactivated_on', models.DateField(blank=True, null=True)),
                ('last_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resources.snapshot')),
            ],
            options={
                'verbose_name_plural': 'business entities',
            },
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['dataset', 'status', '-id'], name='resources_snap_lookup'),
        ),
        migrations.AddIndex(
            model_name='businessentity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_normalized'], name='resources_be_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='businessentity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['agent_normalized'], name='resources_be_agent_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='businessentity',
            index=models.Index(fields=['agent_normalized', 'ra_zip'], name='resources_be_agent_zip'),
        ),
        migrations.AddIndex(
            model_name='businessentity',
            index=models.Index(fields=['ra_city'], name='resources_be_ra_city'),
        ),
        migrations.AddIndex(
            model_name='businessentity',
            index=models.Index(fields=['ho_city'], name='resources_be_ho_city'),
        ),
        migrations.AddIndex(
            model_name='businessentity',
            index=models.Index(fields=['ra_zip'], name='resources_be_ra_zip'),
        ),
        migrations.AddIndex(
            model_name='businessentity',
            index=models.Index(fields=['entity_type'], name='resources_be_type'),
        ),
        migrations.AddIndex(
            model_name='businessentity',
            index=models.Index(fields=['is_active'], name='resources_be_active'),
        ),
    ]
