# Generated by Django 5.1.15 on 2026-05-19 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatTrace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("model", models.CharField(blank=True, max_length=64)),
                ("source_slug", models.CharField(blank=True, max_length=64)),
                ("question", models.TextField(blank=True)),
                ("answer", models.TextField(blank=True)),
                ("tool_calls", models.JSONField(default=list)),
                ("search_queries", models.JSONField(default=list)),
                ("retrieved", models.JSONField(default=list)),
                ("num_tool_calls", models.PositiveIntegerField(default=0)),
                ("num_searches", models.PositiveIntegerField(default=0)),
                ("top_result_used", models.BooleanField(blank=True, null=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_traces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="api_chattra_created_538459_idx"
                    ),
                    models.Index(
                        fields=["top_result_used"],
                        name="api_chattra_top_res_0f0c45_idx",
                    ),
                    models.Index(
                        fields=["source_slug"], name="api_chattra_source__b09553_idx"
                    ),
                ],
            },
        ),
    ]
