# Generated by Django 5.1.15 on 2026-07-10 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_searchlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('feature', models.CharField(max_length=32)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('prompt_tokens', models.PositiveBigIntegerField(default=0)),
                ('completion_tokens', models.PositiveBigIntegerField(default=0)),
                ('cost_microusd', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_llmusag_user_id_fff2ba_idx'), models.Index(fields=['feature'], name='api_llmusag_feature_5bd229_idx'), models.Index(fields=['request_id'], name='api_llmusag_request_8938b3_idx')],
            },
        ),
    ]
